/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <linux/filter.h>
#include <stddef.h>
#include <linux/seccomp.h>
#include <linux/audit.h>
#include "process_uid_define.h"

#define SECCOMP_SYSCALL_ONE_ARG_32(number, jumpLine) \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 0), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, number, 0, jumpLine), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_ALU|BPF_AND|BPF_K, 0xFFFFFFFF), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 2), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 1, 0), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_ALLOW), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_TRAP),

#define SECCOMP_SYSCALL_TWO_ARGS_32(number, jumpLine) \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 0), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, number, 0, jumpLine), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_ALU|BPF_AND|BPF_K, 0xFFFFFFFF), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 12), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 11, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 24), \
    BPF_STMT(BPF_ALU|BPF_AND|BPF_K, 0xFFFFFFFF), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 24), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 2), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 1, 0), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_ALLOW), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_TRAP),

#define SECCOMP_SYSCALL_THREE_ARGS_32(number, jumpLine) \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 0), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, number, 0, jumpLine), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_ALU|BPF_AND|BPF_K, 0xFFFFFFFF), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 22), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 21, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 24), \
    BPF_STMT(BPF_ALU|BPF_AND|BPF_K, 0xFFFFFFFF), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 24), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 12), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 11, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 32), \
    BPF_STMT(BPF_ALU|BPF_AND|BPF_K, 0xFFFFFFFF), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 32), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 2), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 1, 0), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_ALLOW), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_TRAP),

#define SECCOMP_SYSCALL_ONE_ARG_64(number, jumpLine) \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 0), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, number, 0, jumpLine), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 20), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, 0, 0, 10), \
	BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
	BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
	BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 2), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 1, 0), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_ALLOW), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_TRAP),

#define SECCOMP_SYSCALL_TWO_ARGS_64(number, jumpLine) \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 0), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, number, 0, jumpLine), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 20), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, 0, 0, 21), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 13), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 12, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 28), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, 0, 0, 10), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 24), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 24), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 2), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 1, 0), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_ALLOW), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_TRAP),

#define SECCOMP_SYSCALL_THREE_ARGS_64(number, jumpLine) \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 0), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, number, 0, jumpLine), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 20), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, 0, 0, 32), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 16), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 24), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 23, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 28), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, 0, 0, 21), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 24), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 24), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 13), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 12, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 36), \
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, 0, 0, 10), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 32), \
    BPF_STMT(BPF_ALU|BPF_DIV|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ALU|BPF_MUL|BPF_K, BASE_USER_RANGE_FOR_NWEB & 0xffffffff), \
    BPF_STMT(BPF_ST, 0), \
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 32), \
    BPF_STMT(BPF_LDX|BPF_MEM, 0), \
    BPF_STMT(BPF_ALU|BPF_SUB|BPF_X, 0), \
    BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, START_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 0, 2), \
    BPF_JUMP(BPF_JMP|BPF_JGT|BPF_K, END_ID_FOR_RENDER_PROCESS_ISOLATION & 0xffffffff, 1, 0), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_ALLOW), \
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_TRAP),

const struct sock_filter g_nwebspawnSeccompFilter[] = {
    BPF_STMT(BPF_LD|BPF_W|BPF_ABS, 4),
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, AUDIT_ARCH_ARM, 3, 0),
    BPF_JUMP(BPF_JMP|BPF_JEQ|BPF_K, AUDIT_ARCH_AARCH64, 0, 1),
    BPF_JUMP(BPF_JMP|BPF_JA, 346, 0, 0),
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_TRAP),
    // __NR_setfsgid32 216
    SECCOMP_SYSCALL_ONE_ARG_32(216, 12)
    // __NR_setfsgid 139
    SECCOMP_SYSCALL_ONE_ARG_32(139, 12)
    // __NR_setfsuid32 215
    SECCOMP_SYSCALL_ONE_ARG_32(215, 12)
    // __NR_setfsuid 138
    SECCOMP_SYSCALL_ONE_ARG_32(138, 12)
    // __NR_setgid32 214
    SECCOMP_SYSCALL_ONE_ARG_32(214, 12)
    // __NR_setgid 46
    SECCOMP_SYSCALL_ONE_ARG_32(46, 12)
    // __NR_setregid32 204
    SECCOMP_SYSCALL_TWO_ARGS_32(204, 22)
    // __NR_setregid 71
    SECCOMP_SYSCALL_TWO_ARGS_32(71, 22)
    // __NR_setresgid32 210
    SECCOMP_SYSCALL_THREE_ARGS_32(210, 32)
    // __NR_setresgid 170
    SECCOMP_SYSCALL_THREE_ARGS_32(170, 32)
    // __NR_setresuid32 208
    SECCOMP_SYSCALL_THREE_ARGS_32(208, 32)
    // __NR_setresuid 164
    SECCOMP_SYSCALL_THREE_ARGS_32(164, 32)
    // __NR_setreuid32 203
    SECCOMP_SYSCALL_TWO_ARGS_32(203, 22)
    // __NR_setreuid 70
    SECCOMP_SYSCALL_TWO_ARGS_32(70, 22)
    // __NR_setuid32 213
    SECCOMP_SYSCALL_ONE_ARG_32(213, 12)
    // __NR_setuid 23
    SECCOMP_SYSCALL_ONE_ARG_32(23, 10)
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_TRAP),
    // 64 __NR_setfsgid 152
    SECCOMP_SYSCALL_ONE_ARG_64(152, 13)
    // __NR_setfsuid 151
    SECCOMP_SYSCALL_ONE_ARG_64(151, 13)
    // __NR_setgid 144
    SECCOMP_SYSCALL_ONE_ARG_64(144, 13)
    // __NR_setregid 143
    SECCOMP_SYSCALL_TWO_ARGS_64(143, 24)
    // __NR_setresgid 149
    SECCOMP_SYSCALL_THREE_ARGS_64(149, 35)
    // __NR_setresuid 147
    SECCOMP_SYSCALL_THREE_ARGS_64(147, 35)
    // __NR_setreuid 145
    SECCOMP_SYSCALL_TWO_ARGS_64(145, 24)
    // __NR_setuid 146
    SECCOMP_SYSCALL_ONE_ARG_64(146, 11)
    BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_TRAP),
};

const size_t g_nwebspawnSeccompFilterSize = sizeof(g_nwebspawnSeccompFilter)/sizeof(struct sock_filter);