/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import router from '@ohos.router';
@Entry
@Component
struct AccessInfo {
  @State message: string = '设备信息列表';

  build() {
    RelativeContainer() {
      Column() {
        Text(this.message)
          .id('AccessInfoHelloWorld')
          .fontWeight(FontWeight.Bold)
          .alignRules({
            center: { anchor: '__container__', align: VerticalAlign.Center },
            middle: { anchor: '__container__', align: HorizontalAlign.Center }
          })
        //button
        Button('获取设备类型')
          .width('50%')
          .height('50vp')
          .onClick(()=>{
            router.pushUrl({
              url:"pages/deviceType"
            })
          })
        Button('获取产品系列')
          .width('50%')
          .height('50vp')
          .onClick(()=>{
            router.pushUrl({
              url:"pages/productSeries"
            })
          })
        Button('获取设备生产厂家名称')
          .width('50%')
          .height('50vp')
          .onClick(()=>{
            router.pushUrl({
              url:"pages/manufacture"
            })
          })
        Button('获取设备品牌')
          .width('50%')
          .height('50vp')
          .onClick(()=>{
            router.pushUrl({
              url:"pages/brand"
            })
          })
        Button('获取设备序列号')
          .width('50%')
          .height('50vp')
          .onClick(()=>{
            router.pushUrl({
              url:"pages/serial"
            })
          })
      }

    }
    .height('100%')
    .width('100%')
  }
}