/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import deviceInfo from '@ohos.deviceInfo';
import router from '@ohos.router';

@Entry
@Component
struct DeviceType {
  @State message: string = '设备生产厂家';

  build() {
    RelativeContainer() {
      Column() {
        Text(deviceInfo.manufacture)
          .id('manufacture')
          .fontSize(50)
          .fontWeight(FontWeight.Bold)
          .alignRules({
            center: { anchor: '__container__', align: VerticalAlign.Center },
            middle: { anchor: '__container__', align: HorizontalAlign.Center }
          })
        Button('返回主界面')
          .fontSize(30)
          .width('50%')
          .height('50vp')
          .onClick(()=>{
            router.pushUrl({
              url:"pages/accessInfo"
            })
          })
      }

    }
    .height('100%')
    .width('100%')
  }
}